# Generated by Django 4.2.7 on 2023-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0002_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[('0', 'Save for later'), ('1', 'Publish Now')], default=1),
        ),
    ]
