# Generated by Django 4.2.7 on 2023-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0004_alter_recipe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Save for later'), (1, 'Publish Now')], default=0),
        ),
    ]
