# Generated by Django 4.2.7 on 2023-11-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0005_alter_recipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
