# Generated by Django 4.2.7 on 2023-11-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0007_mealplanitem_approved_alter_recipe_status'),
    ]

    operations = [
    ]
